# docker-compose.yml
version: '3.8'

services:
  app:
    image: v4
    ports:
      - "8000:8000"
    volumes:
      - /var/www/amazon-search-analysis:/app
    environment:
      # 可以通过环境变量覆盖.env配置
      - TZ=Asia/Shanghai
    deploy:
      resources:
        limits:
          cpus: '3.5'
          memory: 4G
        reservations:
          cpus: '2.0'
          memory: 2G
    restart: unless-stopped

volumes: {}